//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace News_System.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Comment
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string Comment1 { get; set; }
        public System.DateTime Time { get; set; }
        public Nullable<int> Id_Post { get; set; }
        public bool Deleted { get; set; }
        public bool Approved { get; set; }
        public string Website { get; set; }
        public string Email { get; set; }
        public Nullable<int> Id_Comment { get; set; }
    
        public virtual Post Post { get; set; }
    }
}
