//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace News_System.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Configuration
    {
        public int Id { get; set; }
        public string WebsiteTitle { get; set; }
        public string Slogan { get; set; }
        public string Url { get; set; }
        public string Ads_300 { get; set; }
        public string Ads_970 { get; set; }
        public string Ads_728 { get; set; }
    }
}
