//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace News_System.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Post
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Post()
        {
            this.Comment = new HashSet<Comment>();
            this.Post_Tags = new HashSet<Post_Tags>();
        }
    
        public int Id { get; set; }
        public string Title { get; set; }
        public string Image { get; set; }
        public System.DateTime Time { get; set; }
        //Este es el contenedor de los Tags del View Create
        public string Tags { get; set; }
        public string Description { get; set; }
        public bool Highlight { get; set; }
        public Nullable<int> Id_Category { get; set; }
        public bool DisabledComments { get; set; }
        public bool Deleted { get; set; }
        public Nullable<int> Visits { get; set; }
    
        public virtual Category Category { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Comment> Comment { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Post_Tags> Post_Tags { get; set; }
    }
}
